a='python'
print(a[-5:])
print(a[-2:])
print(a[-3:-1])
print(a[-6:-2])
print(a[-1:-3])
print(a[-6:])
print(a[-5:])
print(a[-99:])
print(a[-2:])
print(a[-1:])
print(a[-7:])
print(a[ : :-1])
print(a[ : :-2])
print(a[ : :-3])
print(a[ : :-4])
print(a[ : :-5])
print(a[ : :-6])